// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjmxckxxxeioodhwlntu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbXhja3h4eGVpb29kaHdsbnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNTkxODQsImV4cCI6MjA1MzYzNTE4NH0.yKtgxJ1LKWCNNkDTyng12uszRPqRYeTbrYaSLzCIWAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);